export enum Event {
  CONNECT = 'connect',
  JOIN = 'join',
  ONJOIN = 'onjoin',
  MESSAGE = 'message',
  LEAVE = 'leave',
  BET = 'bet',
  KICK = 'kick',
  // UPDATE_BET = 'update bet', ??
  // ENDGAME = 'endgame',
  ROOM_DELETE = 'room delete',
  USER_DELETE = 'user delete',
  RULES_UPDATE = 'rules update',
  TITLE_UPDATE = 'title update',
  ISSUE_UPDATE = 'issue update',
  ISSUE_CREATE = 'issue create',
  ISSUE_DELETE = 'issue delete',
  ON_ISSUE_DELETE = 'on issue delete',
  ON_ISSUE_CREATE = 'on issue create',
  VOTE_START = 'vote start',
  VOTE_END = 'vote end',
  VOTE_RESULT = 'vote result',
  PLAY = 'play',
  SET_RULES = 'set rules',
}
